<a href="https://colab.research.google.com/github/tomaszmm3/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'2.0.2'

In [41]:
f = np.arange(10, 13)
x = np.arange(start=1, stop=5, step=0.13)
x.shape
y = np.linspace(start=1, stop=5, num=123)
y.shape
a = np.arange(15)
a.reshape(3,5)
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [62]:
A + 3
A*2
abs(B)
np.add(A, B)
np.subtract(A, B)
np.multiply(A,B)
np.divide(A, B)
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
X*Y
np.dot(X, Y)
X.dot(Y)
X @ Y

array([[  3,   6],
       [-12,   0]])

In [37]:
np.random.randn(10, 2) #rozkład normalny, -1 do 1
np.random.rand(10, 2) #random od 0 do 1
np.random.randint(10, size=(10, 2)) #rand całkowity
np.random.choice([1, 2, 3, 4, 5, 6])
data = np.arange(10)
np.random.shuffle(data)
data
np.exp(4)
np.all([True, True, False])
np.any([True, True, False])
A = np.random.rand(5)
np.argmax(A)
np.argmin(A)
np.argsort(A)
np.max(A)
np.min(A)
A.max()
A.std()

np.float64(0.2861738486658834)

In [50]:
A = np.arange(20)
A = A.reshape(4, -1)
A[1, 2:]

array([7, 8, 9])

In [66]:
for item in A.flat:
  item
A.ravel()
A.T
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A>0
A[A>0]
A[np.bitwise_and(A<5, A>-5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [110]:
v1 = np.array([0, 4])
np.linalg.norm(v1)
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p-q)
q = np.arange(5, 14)
q = q.reshape(3, 3)
np.linalg.det(q)
np.linalg.trace(A)
np.eye(4) #macierz jednostkowa

q = np.array([[0.3, -0.4], [0.1, 0.2]])
p = np.linalg.inv(q)
np.dot(q, p)
np.transpose(q)
q.T

array([[ 0.3,  0.1],
       [-0.4,  0.2]])

In [116]:
#2x+4y=10
#x-y=-1
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])
X = np.dot(np.linalg.inv(A), B)
X

array([[1.],
       [2.]])